### ISSUE TITLE
uui-action-bar is not rendered correctly in safari 

### ISSUE THREAD

**Issue by julczka** [umbraco/Umbraco.UI#226]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

0.2.1

### Bug summary

Action bar gets stretched 

### Steps to reproduce

I was using this markup:
```html
<uui-box>
  <div id="header" slot="header">
    <uui-action-bar>
        <!--Put some buttons here -->
    <uui-action-bar>
  </div>
</uui-box>
```

```css
#header {
    display: flex;
    justify-content: space-between;
    align-items: center;
}
```

### Expected result / actual result

Expected (that how it looks in chrome):
![image](https://user-images.githubusercontent.com/56249914/172323083-222a6e2e-3c6d-41ce-8674-4b7cb5f29cc9.png)

Actual (safari):
![bug2](https://user-images.githubusercontent.com/56249914/172322655-13fcbf25-60e7-4179-bf65-75488951fcbf.jpg)
